### ISSUE TITLE
MHWs OBT not work

### ISSUE THREAD

**Issue by dtlnor** [kagenocookie/REFDumpFormatter#1]
![image](https://github.com/user-attachments/assets/e452e61b-d7c7-4d4a-a784-e1099d2dbd7d)
parser value is 
```
"System.ValueTuple`2[[System.Collections.Generic.SortedSet`1.Node[[System.Collections.Generic.KeyValuePair`2[[System.Int32, System.Private.CoreLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[System.Collections.Generic.List`1[[app.cGUIFilteringIconDispData, System.Private.CoreLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[System.Collections.Generic.SortedSet`1.Node[[System.Collections.Generic.KeyValuePair`2[[System.Int32, System.Private.CoreLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[System.Collections.Generic.List`1[[app.cGUIFilteringIconDispData, System.Private.CoreLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLi[]"
```

il2cpp dump
https://gofile.io/d/QbYiX7

**Comment by kagenocookie** [comment]
Had a fix ready for a while but kinda forgot about it. Try again with the latest release.

**Comment by dtlnor** [comment]
```
il2cpp dump file location (folder or full filename): G:\mhwsdemo\steamapps\common\MonsterHunterWildsBetatest\il2cpp_dump.json
output location (Default: G:\mhwsdemo\steamapps\common\MonsterHunterWildsBetatest\il2cpp_dump.json/lang_reference):
Output format: [C]sharp or [L]ua: L
Separate files per [c]lass or per [n]amespace: n
Emit all overloaded methods: [y/n] y
Include field byte offsets: [y/n] n
Reading dump file: G:\mhwsdemo\steamapps\common\MonsterHunterWildsBetatest\il2cpp_dump.json. This might take a while...
Writing output to G:\mhwsdemo\steamapps\common\MonsterHunterWildsBetatest\lua_reference
Unhandled exception. System.Exception: Hmm is this right?
   at REFDumpFormatter.Classname.ParseBracketed(StringParser& parser, GeneratorContext ctx)
   at REFDumpFormatter.Classname.ParseBracketedElement(StringParser& parser, GeneratorContext ctx)
   at REFDumpFormatter.Classname.ParseBracketed(StringParser& parser, GeneratorContext ctx)
   at REFDumpFormatter.Classname.Parse(StringParser& parser, GeneratorContext ctx, Boolean ignoreNonDefinitions)
   at REFDumpFormatter.Classname.Parse(String name, GeneratorContext ctx, Classname containingClass, Boolean ignoreNonDefinitions)
   at REFDumpFormatter.GenerateLua.<>c__DisplayClass7_0.<HandleClass>b__8(ParamDef p, Int32 i)
   at System.Linq.Enumerable.SelectIterator[TSource,TResult](IEnumerable`1 source, Func`3 selector)+MoveNext()
   at System.Linq.Enumerable.SelectIterator[TSource,TResult](IEnumerable`1 source, Func`3 selector)+MoveNext()
   at System.String.Join(String separator, IEnumerable`1 values)
   at REFDumpFormatter.GenerateLua.HandleClass(StringBuilder sb, HashSet`1 props, ObjectDef item, ClassSummary cls, String flags, GeneratorContext ctx)
   at REFDumpFormatter.GenerateLua.GenerateOutput(OutputOptions options, IEnumerable`1 entries)
   at Program.<Main>$(String[] args)
```

Still having issue

**Comment by kagenocookie** [comment]
This one system type is too long so it's missing the full signature in the il2cpp dump. I've now added a workaround in v1.4 to make such types get ignored instead if they fail, so the rest of the output still ends up fine. 

Might look into REF's side for why these are missing at some point, but it's just one such class here with 5 references so it's not too much of a loss I'd say.
